### ISSUE TITLE
Missing compiled code in the package

### ISSUE THREAD

**Issue by eugeny-dementev** [stackblogger/link-meta-extractor#1]
Deployed package missing `dist` directory specified for compiled files

https://www.npmjs.com/package/link-meta-extractor?activeTab=code

**Comment by stackblogger** [comment]
> Deployed package missing `dist` directory specified for compiled files
> 
> https://www.npmjs.com/package/link-meta-extractor?activeTab=code

Let me test and fix it.

**Comment by stackblogger** [comment]
> Deployed package missing `dist` directory specified for compiled files
> 
> https://www.npmjs.com/package/link-meta-extractor?activeTab=code

dist was somehow missed while publishing. I have published a new version with the dist folder. 
You can re-install the package with the latest version and you should be able to use it.

Thanks for noticing this issue.
